baseURL = "https://conamex.github.io"
languageCode = "en-us"
title = "CONAMEX International"

[params]
    author = "Robert L'Esperance"
    description = "Enabling People to Do New Things More Efficiently Since 1985"
    accent = "darkblue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"

[markup.goldmark.renderer]
  unsafe= true

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/mission/"
    name = "Mission"
    weight = 3

[[menu.main]]
    url = "/software/"
    name = "Software"
    weight = 4

[[menu.main]]
    url = "/awards/"
    name = "Awards"
    weight = 5

[[menu.main]]
    url = "/press/"
    name = "Press"
    weight = 6

[[menu.main]]
    url = "/contact/"
    name = "Contact Us"
    weight = 7

[[menu.icon]]
    url = "https://www.linkedin.com/company/conamex-international/about/"
    name = "linkedin"

[[menu.icon]]
    url = "https://www.facebook.com/conamex"
    name = "facebook"
