baseURL = "http://conamex.com/"
languageCode = "en-us"
title = "CONAMEX International"
theme = "minimal"

[params]
    author = "Robert L'Esperance"
    description = "Enabling People to Do New Things More Efficiently since 1985"
    accent = "darkblue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/mission/"
    name = "Mission"
    weight = 3

[[menu.main]]
    url = "/awards/"
    name = "Awards"
    weight = 4

[[menu.main]]
    url = "/press/"
    name = "Press"
    weight = 4

[[menu.icon]]
    url = "mailto:software@conamex.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/company/conamex-international/about/"
    name = "linkedin"
    weight = 4
